apiVersion: apps/v1
kind: Deployment
metadata:
  name: flux
spec:
  template:
    spec:
      containers:
        - name: flux
          args:
            - --manifest-generation=true
            - --memcached-hostname=flux-memcached.flux-system
            - --memcached-service=
            - --git-poll-interval=1m
            - --sync-interval=1m
            - --ssh-keygen-dir=/var/fluxd/keygen
            - --k8s-allow-namespace=api
            - --git-url=git@github.com:dakario/Force-Covid-19-backend.git
            - --git-branch=gitops
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flux
subjects:
  - kind: ServiceAccount
    name: flux
    namespace: api
