apiVersion: v1
kind: Config
preferences: {}
users: []
clusters: []
current-context: default
contexts:
  - context:
      cluster: ""
      namespace: Force-Covid-19-Front
      user: ""
    name: default
